[App]
Name = "ai.h2o.hashtag_run"
Version = "0.1729.1"
Title = "Twitter Streamer"
Description = "This application fetch twitter stream for a configured hashtags and provides insights"
LongDescription="about.md"
Category = "Data Science"
Keywords =  ["Data Science", "Wave", "Open Source", "Sentiment Analysis"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
